# Generated by Django 5.2.6 on 2025-09-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория консультаций',
                'verbose_name_plural': 'Категории консультаций',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('pediatrician', 'Педиатр'), ('neurologist', 'Невролог'), ('nutritionist', 'Диетолог'), ('psychologist', 'Детский психолог'), ('lactation', 'Консультант по грудному вскармливанию'), ('sleep', 'Консультант по сну'), ('development', 'Специалист по развитию'), ('other', 'Другое')], max_length=20, verbose_name='Специализация')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Номер лицензии')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость консультации')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для консультаций')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('total_consultations', models.PositiveIntegerField(default=0, verbose_name='Всего консультаций')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль консультанта',
                'verbose_name_plural': 'Профили консультантов',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тема консультации')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('urgency', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('urgent', 'Срочно')], default='medium', max_length=10, verbose_name='Срочность')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=15, verbose_name='Статус')),
                ('child_age_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст ребенка (месяцы)')),
                ('child_symptoms', models.TextField(blank=True, verbose_name='Симптомы')),
                ('medical_history', models.TextField(blank=True, verbose_name='Медицинская история')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultant.consultantprofile')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='accounts.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('question', 'Вопрос'), ('answer', 'Ответ'), ('follow_up', 'Уточнение')], default='question', max_length=10, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='consultation_attachments/', verbose_name='Вложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultant.consultation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение консультации',
                'verbose_name_plural': 'Сообщения консультаций',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='consultant.consultation')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отзыв о консультации',
                'verbose_name_plural': 'Отзывы о консультациях',
            },
        ),
    ]
