# Generated by Django 5.2.6 on 2025-09-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0001_initial'),
        ('healthcare', '0002_doctor_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='healthcare.doctor'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consultant.consultantprofile'),
        ),
    ]
