# Generated by Django 5.2.6 on 2025-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant', '0002_consultation_doctor_alter_consultation_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='consultation_attachments/', verbose_name='Документы и анализы'),
        ),
    ]
