# Generated by Django 5.2.6 on 2025-09-06 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название семьи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Семья',
                'verbose_name_plural': 'Семьи',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('parent', 'Родитель'), ('writer', 'Писатель')], default='parent', max_length=10, verbose_name='Тип пользователя')),
                ('role', models.CharField(blank=True, choices=[('mom', 'Мама'), ('dad', 'Папа')], max_length=3, null=True, verbose_name='Роль')),
                ('child_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя ребёнка')),
                ('child_birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения ребёнка')),
                ('family_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код семьи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='accounts.family', verbose_name='Семья')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль родителя',
                'verbose_name_plural': 'Профили родителей',
            },
        ),
    ]
