# Generated by Django 5.2.6 on 2025-09-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ребёнка')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=6, null=True, verbose_name='Пол')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.family', verbose_name='Семья')),
            ],
            options={
                'verbose_name': 'Ребёнок',
                'verbose_name_plural': 'Дети',
                'ordering': ['-created_at'],
            },
        ),
    ]
