# Generated by Django 5.2.6 on 2025-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город проживания'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Место работы'),
        ),
    ]
