# Generated by Django 5.2.6 on 2025-09-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parentprofile_birth_date_parentprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='journalism_experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт в журналистике'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='writing_motivation',
            field=models.TextField(blank=True, null=True, verbose_name='Почему хотите стать писателем?'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Сколько лет опыта?'),
        ),
    ]
