# Generated by Django 5.2.6 on 2025-09-06 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parentprofile_journalism_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('password', models.CharField(blank=True, max_length=128, verbose_name='Пароль')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, upload_to='writers/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('writing_motivation', models.TextField(blank=True, verbose_name='Почему хочет стать писателем')),
                ('journalism_experience', models.TextField(blank=True, verbose_name='Опыт в журналистике')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Годы опыта')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Языки')),
                ('articles_count', models.PositiveIntegerField(default=0, verbose_name='Количество статей')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Общее количество просмотров')),
                ('total_read_time', models.PositiveIntegerField(default=0, verbose_name='Общее время чтения (мин)')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_writer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль писателя',
                'verbose_name_plural': 'Профили писателей',
                'ordering': ['-created_at'],
            },
        ),
    ]
