# Generated by Django 5.2.6 on 2025-09-07 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_writerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('writing_motivation', models.TextField(verbose_name='Почему хотите стать писателем?')),
                ('journalism_experience', models.TextField(verbose_name='Опыт в журналистике')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Годы опыта')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('languages', models.CharField(blank=True, max_length=200, verbose_name='Языки')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('review_notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рассмотрел')),
            ],
            options={
                'verbose_name': 'Заявка писателя',
                'verbose_name_plural': 'Заявки писателей',
                'ordering': ['-created_at'],
            },
        ),
    ]
