# Generated by Django 5.2.6 on 2025-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_writerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='writerapplication',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='writerapplication',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Логин'),
        ),
    ]
