# Generated by Django 5.2.6 on 2025-09-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_writerapplication_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='parent_photos/', verbose_name='Фотография профиля'),
        ),
    ]
