# Generated by Django 5.2.6 on 2025-09-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='support/avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Контакт для экстренных случаев'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон экстренного контакта'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='is_team_lead',
            field=models.BooleanField(default=False, verbose_name='Руководитель команды'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='supportprofile',
            name='skills',
            field=models.TextField(blank=True, verbose_name='Навыки и компетенции'),
        ),
    ]
