# Generated by Django 5.2.6 on 2025-09-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_supportprofile_address_supportprofile_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDeletionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('doctor', 'Отзыв о враче'), ('facility', 'Отзыв об учреждении')], max_length=20, verbose_name='Тип отзыва')),
                ('target_name', models.CharField(max_length=200, verbose_name='Название объекта')),
                ('reason', models.TextField(verbose_name='Причина удаления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('support_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник техподдержки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление об удалении отзыва',
                'verbose_name_plural': 'Уведомления об удалении отзывов',
                'ordering': ['-created_at'],
            },
        ),
    ]
