# Generated by Django 5.2.6 on 2025-09-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_reviewdeletionnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewDeletionNotification',
        ),
    ]
