# Generated by Django 5.2.6 on 2025-09-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('social_media', models.CharField(blank=True, max_length=200, verbose_name='Социальные сети')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='writer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль писателя',
                'verbose_name_plural': 'Профили писателей',
            },
        ),
        migrations.CreateModel(
            name='WriterDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок')),
                ('writer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='writer.writerprofile')),
            ],
            options={
                'verbose_name': 'Дашборд писателя',
                'verbose_name_plural': 'Дашборды писателей',
            },
        ),
    ]
