# Generated by Django 5.2.6 on 2025-09-06 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment_bloglike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='read_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Время чтения (мин)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На одобрении'), ('approved', 'Одобрено'), ('published', 'Опубликовано'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.CreateModel(
            name='BlogAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_duration', models.PositiveIntegerField(default=0, verbose_name='Время просмотра (сек)')),
                ('read_progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс чтения (%)')),
                ('user_age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст пользователя')),
                ('user_gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский'), ('other', 'Другой')], max_length=10, verbose_name='Пол пользователя')),
                ('user_city', models.CharField(blank=True, max_length=100, verbose_name='Город пользователя')),
                ('device_type', models.CharField(choices=[('desktop', 'Десктоп'), ('mobile', 'Мобильный'), ('tablet', 'Планшет')], default='desktop', max_length=20, verbose_name='Тип устройства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='blog.blogpost', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_analytics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Аналитика статьи',
                'verbose_name_plural': 'Аналитика статей',
                'unique_together': {('blog_post', 'user')},
            },
        ),
    ]
