# Generated by Django 5.2.6 on 2025-09-06 17:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('icon', models.CharField(help_text='Bootstrap Icons класс', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(help_text='Bootstrap цвет класс', max_length=20, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория медицинского учреждения',
                'verbose_name_plural': 'Категории медицинских учреждений',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthcareFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('working_hours', models.TextField(blank=True, verbose_name='Часы работы')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='healthcare.healthcarecategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Медицинское учреждение',
                'verbose_name_plural': 'Медицинские учреждения',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('qualifications', models.TextField(blank=True, verbose_name='Квалификации')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, upload_to='doctors/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='healthcare.healthcarefacility', verbose_name='Медицинское учреждение')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
                'ordering': ['-rating', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный отзыв')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='healthcare.doctor', verbose_name='Врач')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о враче',
                'verbose_name_plural': 'Отзывы о врачах',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок отзыва')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('visit_date', models.DateField(verbose_name='Дата посещения')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Анонимный отзыв')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='healthcare.healthcarefacility', verbose_name='Медицинское учреждение')),
            ],
            options={
                'verbose_name': 'Отзыв о медицинском учреждении',
                'verbose_name_plural': 'Отзывы о медицинских учреждениях',
                'ordering': ['-created_at'],
                'unique_together': {('facility', 'user')},
            },
        ),
    ]
