# Generated by Django 5.2.6 on 2025-09-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_doctor_consultant'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='Пароль'),
        ),
    ]
