# Generated by Django 5.2.6 on 2025-09-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Награды и достижения'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_duration',
            field=models.PositiveIntegerField(default=30, verbose_name='Длительность консультации (мин)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена консультации (сом)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available_for_consultation',
            field=models.BooleanField(default=True, verbose_name='Доступен для консультаций'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.CharField(blank=True, max_length=200, verbose_name='Языки'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='publications',
            field=models.TextField(blank=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.TextField(blank=True, verbose_name='Часы работы'),
        ),
    ]
