# Generated by Django 5.2.6 on 2025-09-06 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyCry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('minutes_cried', models.IntegerField(verbose_name='Минуты плача')),
                ('reason', models.CharField(choices=[('hunger', 'Голод'), ('tired', 'Усталость'), ('discomfort', 'Дискомфорт'), ('pain', 'Боль'), ('attention', 'Внимание'), ('other', 'Другое')], max_length=50, verbose_name='Причина плача')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cry_records', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cry_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись плача',
                'verbose_name_plural': 'Записи плача',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BabyFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('feeding_type', models.CharField(choices=[('breast', 'Грудное молоко'), ('formula', 'Смесь'), ('solid', 'Прикорм'), ('mixed', 'Смешанное')], max_length=20, verbose_name='Тип питания')),
                ('amount', models.CharField(blank=True, max_length=50, verbose_name='Количество')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись кормления',
                'verbose_name_plural': 'Записи кормления',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='BabyGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рост (см)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Вес (кг)')),
                ('date', models.DateField(verbose_name='Дата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись роста и веса',
                'verbose_name_plural': 'Записи роста и веса',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BabySleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hours_slept', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Часы сна')),
                ('sleep_quality', models.CharField(choices=[('excellent', 'Отлично'), ('good', 'Хорошо'), ('fair', 'Удовлетворительно'), ('poor', 'Плохо')], max_length=20, verbose_name='Качество сна')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись сна',
                'verbose_name_plural': 'Записи сна',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
