# Generated by Django 5.2.6 on 2025-09-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parentprofile_birth_date_parentprofile_city_and_more'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='babycry',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cry_records', to='accounts.child', verbose_name='Ребёнок'),
        ),
        migrations.AddField(
            model_name='babyfeeding',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='accounts.child', verbose_name='Ребёнок'),
        ),
        migrations.AddField(
            model_name='babygrowth',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='accounts.child', verbose_name='Ребёнок'),
        ),
        migrations.AddField(
            model_name='babysleep',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='accounts.child', verbose_name='Ребёнок'),
        ),
    ]
