# Generated by Django 5.2.6 on 2025-09-06 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_parentprofile_birth_date_parentprofile_city_and_more'),
        ('tracker', '0002_babycry_child_babyfeeding_child_babygrowth_child_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='Название вакцины')),
                ('date_given', models.DateField(verbose_name='Дата вакцинации')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Следующая вакцинация')),
                ('doctor_name', models.CharField(blank=True, max_length=100, verbose_name='Имя врача')),
                ('clinic_name', models.CharField(blank=True, max_length=200, verbose_name='Название клиники')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='Номер партии')),
                ('reaction', models.TextField(blank=True, verbose_name='Реакция на вакцину')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='accounts.child', verbose_name='Ребёнок')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='accounts.family')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись прививки',
                'verbose_name_plural': 'Записи прививок',
                'ordering': ['-date_given'],
            },
        ),
    ]
