# Generated by Django 5.2.6 on 2025-09-06 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system_announcement', 'Системное объявление'), ('system_update', 'Обновление системы'), ('system_maintenance', 'Техническое обслуживание'), ('consultation_request', 'Запрос на консультацию'), ('consultation_accepted', 'Консультация принята'), ('consultation_rejected', 'Консультация отклонена'), ('consultation_completed', 'Консультация завершена'), ('consultation_message', 'Сообщение в консультации'), ('forum_topic_reply', 'Ответ в теме форума'), ('forum_topic_created', 'Создана новая тема'), ('forum_topic_solution', 'Тема отмечена как решение'), ('forum_topic_deleted', 'Тема удалена'), ('review_left', 'Оставлен отзыв'), ('review_approved', 'Отзыв одобрен'), ('review_deleted', 'Отзыв удален'), ('review_response', 'Ответ на отзыв'), ('blog_post_published', 'Опубликована статья блога'), ('blog_post_approved', 'Статья блога одобрена'), ('blog_post_rejected', 'Статья блога отклонена'), ('blog_comment', 'Комментарий к статье'), ('facility_new_review', 'Новый отзыв об учреждении'), ('facility_new_doctor_review', 'Новый отзыв о враче'), ('facility_new_appointment', 'Новая запись к врачу'), ('facility_request_approved', 'Заявка учреждения одобрена'), ('facility_request_rejected', 'Заявка учреждения отклонена'), ('tracker_milestone', 'Достигнута веха развития'), ('tracker_vaccination_due', 'Подошло время прививки'), ('tracker_appointment_reminder', 'Напоминание о приеме'), ('support_ticket_created', 'Создан тикет техподдержки'), ('support_ticket_updated', 'Тикет обновлен'), ('support_ticket_resolved', 'Тикет решен')], max_length=50, unique=True, verbose_name='Тип уведомления')),
                ('title_template', models.CharField(max_length=200, verbose_name='Шаблон заголовка')),
                ('message_template', models.TextField(verbose_name='Шаблон сообщения')),
                ('send_email', models.BooleanField(default=True, verbose_name='Отправлять email')),
                ('send_push', models.BooleanField(default=True, verbose_name='Отправлять push')),
                ('default_priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email уведомления включены')),
                ('email_consultations', models.BooleanField(default=True, verbose_name='Email о консультациях')),
                ('email_forum', models.BooleanField(default=True, verbose_name='Email о форуме')),
                ('email_reviews', models.BooleanField(default=True, verbose_name='Email об отзывах')),
                ('email_blog', models.BooleanField(default=True, verbose_name='Email о блоге')),
                ('email_system', models.BooleanField(default=True, verbose_name='Email системные')),
                ('email_tracker', models.BooleanField(default=True, verbose_name='Email о трекере')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Push уведомления включены')),
                ('push_consultations', models.BooleanField(default=True, verbose_name='Push о консультациях')),
                ('push_forum', models.BooleanField(default=True, verbose_name='Push о форуме')),
                ('push_reviews', models.BooleanField(default=True, verbose_name='Push об отзывах')),
                ('push_blog', models.BooleanField(default=True, verbose_name='Push о блоге')),
                ('push_system', models.BooleanField(default=True, verbose_name='Push системные')),
                ('push_tracker', models.BooleanField(default=True, verbose_name='Push о трекере')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Немедленно'), ('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('never', 'Никогда')], default='immediate', max_length=20, verbose_name='Частота уведомлений')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system_announcement', 'Системное объявление'), ('system_update', 'Обновление системы'), ('system_maintenance', 'Техническое обслуживание'), ('consultation_request', 'Запрос на консультацию'), ('consultation_accepted', 'Консультация принята'), ('consultation_rejected', 'Консультация отклонена'), ('consultation_completed', 'Консультация завершена'), ('consultation_message', 'Сообщение в консультации'), ('forum_topic_reply', 'Ответ в теме форума'), ('forum_topic_created', 'Создана новая тема'), ('forum_topic_solution', 'Тема отмечена как решение'), ('forum_topic_deleted', 'Тема удалена'), ('review_left', 'Оставлен отзыв'), ('review_approved', 'Отзыв одобрен'), ('review_deleted', 'Отзыв удален'), ('review_response', 'Ответ на отзыв'), ('blog_post_published', 'Опубликована статья блога'), ('blog_post_approved', 'Статья блога одобрена'), ('blog_post_rejected', 'Статья блога отклонена'), ('blog_comment', 'Комментарий к статье'), ('facility_new_review', 'Новый отзыв об учреждении'), ('facility_new_doctor_review', 'Новый отзыв о враче'), ('facility_new_appointment', 'Новая запись к врачу'), ('facility_request_approved', 'Заявка учреждения одобрена'), ('facility_request_rejected', 'Заявка учреждения отклонена'), ('tracker_milestone', 'Достигнута веха развития'), ('tracker_vaccination_due', 'Подошло время прививки'), ('tracker_appointment_reminder', 'Напоминание о приеме'), ('support_ticket_created', 'Создан тикет техподдержки'), ('support_ticket_updated', 'Тикет обновлен'), ('support_ticket_resolved', 'Тикет решен')], max_length=50, verbose_name='Тип уведомления')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=10, verbose_name='Приоритет')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID связанного объекта')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип связанного объекта')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
