# Generated by Django 5.2.6 on 2025-09-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system_announcement', 'Системное объявление'), ('system_update', 'Обновление системы'), ('system_maintenance', 'Техническое обслуживание'), ('consultation_request', 'Запрос на консультацию'), ('consultation_accepted', 'Консультация принята'), ('consultation_rejected', 'Консультация отклонена'), ('consultation_completed', 'Консультация завершена'), ('consultation_message', 'Сообщение в консультации'), ('forum_topic_reply', 'Ответ в теме форума'), ('forum_topic_created', 'Создана новая тема'), ('forum_topic_solution', 'Тема отмечена как решение'), ('forum_topic_deleted', 'Тема удалена'), ('forum_post_quoted', 'Вас процитировали в форуме'), ('review_left', 'Оставлен отзыв'), ('review_approved', 'Отзыв одобрен'), ('review_deleted', 'Отзыв удален'), ('review_response', 'Ответ на отзыв'), ('blog_post_published', 'Опубликована статья блога'), ('blog_post_approved', 'Статья блога одобрена'), ('blog_post_rejected', 'Статья блога отклонена'), ('blog_comment', 'Комментарий к статье'), ('writer_application_submitted', 'Подана заявка писателя'), ('writer_application_approved', 'Заявка писателя одобрена'), ('writer_application_rejected', 'Заявка писателя отклонена'), ('facility_new_review', 'Новый отзыв об учреждении'), ('facility_new_doctor_review', 'Новый отзыв о враче'), ('facility_new_appointment', 'Новая запись к врачу'), ('facility_request_approved', 'Заявка учреждения одобрена'), ('facility_request_rejected', 'Заявка учреждения отклонена'), ('tracker_milestone', 'Достигнута веха развития'), ('tracker_vaccination_due', 'Подошло время прививки'), ('tracker_appointment_reminder', 'Напоминание о приеме'), ('support_ticket_created', 'Создан тикет техподдержки'), ('support_ticket_updated', 'Тикет обновлен'), ('support_ticket_resolved', 'Тикет решен')], max_length=50, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('system_announcement', 'Системное объявление'), ('system_update', 'Обновление системы'), ('system_maintenance', 'Техническое обслуживание'), ('consultation_request', 'Запрос на консультацию'), ('consultation_accepted', 'Консультация принята'), ('consultation_rejected', 'Консультация отклонена'), ('consultation_completed', 'Консультация завершена'), ('consultation_message', 'Сообщение в консультации'), ('forum_topic_reply', 'Ответ в теме форума'), ('forum_topic_created', 'Создана новая тема'), ('forum_topic_solution', 'Тема отмечена как решение'), ('forum_topic_deleted', 'Тема удалена'), ('forum_post_quoted', 'Вас процитировали в форуме'), ('review_left', 'Оставлен отзыв'), ('review_approved', 'Отзыв одобрен'), ('review_deleted', 'Отзыв удален'), ('review_response', 'Ответ на отзыв'), ('blog_post_published', 'Опубликована статья блога'), ('blog_post_approved', 'Статья блога одобрена'), ('blog_post_rejected', 'Статья блога отклонена'), ('blog_comment', 'Комментарий к статье'), ('writer_application_submitted', 'Подана заявка писателя'), ('writer_application_approved', 'Заявка писателя одобрена'), ('writer_application_rejected', 'Заявка писателя отклонена'), ('facility_new_review', 'Новый отзыв об учреждении'), ('facility_new_doctor_review', 'Новый отзыв о враче'), ('facility_new_appointment', 'Новая запись к врачу'), ('facility_request_approved', 'Заявка учреждения одобрена'), ('facility_request_rejected', 'Заявка учреждения отклонена'), ('tracker_milestone', 'Достигнута веха развития'), ('tracker_vaccination_due', 'Подошло время прививки'), ('tracker_appointment_reminder', 'Напоминание о приеме'), ('support_ticket_created', 'Создан тикет техподдержки'), ('support_ticket_updated', 'Тикет обновлен'), ('support_ticket_resolved', 'Тикет решен')], max_length=50, unique=True, verbose_name='Тип уведомления'),
        ),
    ]
